## Pytorch For Begginer

#### importing Torch

In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    print("GPU is available")


else:
    print("GPU is not available , CPU is using")

GPU is not available , CPU is using


### creating a tensor

In [6]:
a = torch.empty(2,3)
print(a)


tensor([[-1.5902e-30,  8.8002e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


### check a type

In [7]:
type(a)

torch.Tensor

#### using a zeros

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### using ones

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

#### using rand

In [10]:
torch.rand(2,3)

tensor([[0.3534, 0.6839, 0.9418],
        [0.9273, 0.2227, 0.4582]])

#### manual seed

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

#### using tensor

In [13]:
torch.tensor([[1,2,3,4] , [1,2,3,4]])

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

#### arrange

In [15]:
print("arrange :"  , (torch.arange(0 , 12 , 2)))

arrange : tensor([ 0,  2,  4,  6,  8, 10])


### Create a 1D Tensor

In [16]:
torch.tensor([10, 20, 30, 40, 50])

tensor([10, 20, 30, 40, 50])

In [17]:
import torch

x = torch.tensor([10, 20, 30, 40, 50])

print(x)

tensor([10, 20, 30, 40, 50])


#### Create a 2D Tensor

In [18]:
import torch as tr
x = torch.tensor([[1, 2, 3],
 [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


#### Create a Tensor of Zeros

In [19]:
import torch
x = torch.zeros(5)
print(x)

tensor([0., 0., 0., 0., 0.])


#### Create a Tensor of Ones

In [20]:
x = torch.ones(3 , 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


#### Create a Tensor with arange()

In [21]:
import torch

tensor = torch.arange(1, 11)

print(tensor)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


### Create a Random Tensor

In [22]:
x = torch.rand(2,3)
print(x)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


#### . Create a Tensor from a Python List

In [23]:
import torch

# Create a Python list
numbers = [5, 10, 15, 20, 25]

# Convert the list into a PyTorch tensor
tensor = torch.tensor(numbers)

# Print the tensor
print("Tensor:", tensor)

# Print the data type
print("Data type:", tensor.dtype)

# Print the shape
print("Shape:", tensor.shape)

Tensor: tensor([ 5, 10, 15, 20, 25])
Data type: torch.int64
Shape: torch.Size([5])


#### eye

In [24]:
print("Eye : " , torch.eye(5))

Eye :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


#### shape of the array

In [2]:
import torch
x = torch.tensor([[1,2,3,4],[1,2,3,4]])
x.shape
print(x)

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])


#### Create a tensor:

In [4]:
x = torch.tensor([10, 20, 30, 40, 50])
print(x)
print("shape of the tensor : " , x.shape)

print("the numbers of the dimension : ", x.dim())

tensor([10, 20, 30, 40, 50])
shape of the tensor :  torch.Size([5])
the numbers of the dimension :  1


#### Create a 2D Tensor and Find Its Shape

In [5]:
import torch

x = torch.arange(24).reshape(2, 3, 4)

print("Tensor:")
print(x)

print("Shape of the tensor:", x.shape)

print("Number of dimensions:", x.ndim)

Tensor:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Shape of the tensor: torch.Size([2, 3, 4])
Number of dimensions: 3


#### Check the Shape of a Random Tensor

In [6]:
import torch
x = torch.rand(2)
print(x)

tensor([0.3743, 0.3118])
