## Pytorch For Begginer

#### importing Torch

In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    print("GPU is available")


else:
    print("GPU is not available , CPU is using")

GPU is not available , CPU is using


### creating a tensor

In [6]:
a = torch.empty(2,3)
print(a)


tensor([[-1.5902e-30,  8.8002e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


### check a type

In [7]:
type(a)

torch.Tensor

#### using a zeros

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### using ones

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])